import unittest

from core.constants import (
    CURRENCY_ALUMINUM,
    CURRENCY_COPPER,
    CURRENCY_DOLLAR,
    CURRENCY_EURO,
    CURRENCY_GOLD,
    CURRENCY_IRON,
    CURRENCY_NDAQ,
    CURRENCY_OIL,
    CURRENCY_OPTIONS,
    CURRENCY_RUB,
    CURRENCY_SILVER,
    CURRENCY_SP500,
    CURRENCY_UAH,
    CURRENCY_US_HOUSING,
    COFER_CURRENCY_OPTIONS,
    COFER_DEFAULT_CURRENCIES,
    POWERLAW_SERIES_DOGECOIN_BTC,
    POWERLAW_SERIES_BITCOIN_MARKET_CAP,
    POWERLAW_SERIES_BITCOIN_NETWORK_SIMULATION,
    POWERLAW_SERIES_BITCOIN_VOLATILITY,
    POWERLAW_SERIES_FILECOIN_BTC,
    POWERLAW_SERIES_LITECOIN_BTC,
    POWERLAW_SERIES_LIGHTNING_CAPACITY,
    POWERLAW_SERIES_LIGHTNING_NODES,
    POWERLAW_SERIES_LIQUID_BTC,
    POWERLAW_SERIES_LIQUID_TRANSACTIONS,
    POWERLAW_SERIES_MONERO_BTC,
    POWERLAW_SERIES_OPTIONS,
    POWERLAW_SERIES_USDT_SUPPLY,
    POWERLAW_SERIES_US_M2,
)


class TestConstantsSeries(unittest.TestCase):
    def test_currency_options_follow_requested_order(self):
        self.assertEqual(
            CURRENCY_OPTIONS,
            [
                CURRENCY_EURO,
                CURRENCY_DOLLAR,
                CURRENCY_UAH,
                CURRENCY_RUB,
                CURRENCY_OIL,
                CURRENCY_IRON,
                CURRENCY_ALUMINUM,
                CURRENCY_COPPER,
                CURRENCY_US_HOUSING,
                CURRENCY_SILVER,
                CURRENCY_SP500,
                CURRENCY_GOLD,
                CURRENCY_NDAQ,
            ],
        )

    def test_powerlaw_series_options_include_lightning_and_liquid_series(self):
        self.assertIn(POWERLAW_SERIES_LIGHTNING_NODES, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_LIGHTNING_CAPACITY, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_LIQUID_BTC, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_LIQUID_TRANSACTIONS, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_FILECOIN_BTC, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_MONERO_BTC, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_LITECOIN_BTC, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_DOGECOIN_BTC, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_BITCOIN_NETWORK_SIMULATION, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_BITCOIN_MARKET_CAP, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_BITCOIN_VOLATILITY, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_US_M2, POWERLAW_SERIES_OPTIONS)
        self.assertIn(POWERLAW_SERIES_USDT_SUPPLY, POWERLAW_SERIES_OPTIONS)

    def test_cofer_currency_options_include_major_reserve_currencies(self):
        self.assertEqual(COFER_DEFAULT_CURRENCIES, ["BTC", "USD", "EUR", "JPY", "CNY"])
        for currency in ["BTC", "USD", "EUR", "JPY", "GBP", "CNY", "AUD", "CAD", "CHF", "Other"]:
            self.assertIn(currency, COFER_CURRENCY_OPTIONS)


if __name__ == "__main__":
    unittest.main()
