import pandas as pd

# App/meta
APP_VERSION = "1.1.1"
GENESIS_DATE = pd.to_datetime("2009-01-03")
DIFFICULTY_HASHRATE_ANALYSIS_START_DATE = pd.to_datetime("2010-07-18")
DIFFICULTY_HASHRATE_ANALYSIS_START_ABS_DAYS = int(
    (DIFFICULTY_HASHRATE_ANALYSIS_START_DATE - GENESIS_DATE).days
)

# Model defaults
DEFAULT_A = -16.480
DEFAULT_B = 5.681
DEFAULT_EURO_A = -16.950
DEFAULT_EURO_B = 5.796
DEFAULT_GOLD_A = -18.738
DEFAULT_GOLD_B = 5.405
DEFAULT_REVENUE_A = -7.906
DEFAULT_REVENUE_B = 4.168
DEFAULT_DIFFICULTY_A = -27.916
DEFAULT_DIFFICULTY_B = 11.276
DEFAULT_HASHRATE_A = -32.773
DEFAULT_HASHRATE_B = 11.199
DEFAULT_LIGHTNING_NODES_A = -11.423
DEFAULT_LIGHTNING_NODES_B = 4.182
DEFAULT_LIGHTNING_CAPACITY_A = -23.518
DEFAULT_LIGHTNING_CAPACITY_B = 7.273
DEFAULT_LIQUID_BTC_A = -30.076
DEFAULT_LIQUID_BTC_B = 9.010
DEFAULT_LIQUID_TRANSACTIONS_A = -16.736
DEFAULT_LIQUID_TRANSACTIONS_B = 5.566
DEFAULT_FILECOIN_BTC_A = 37.119
DEFAULT_FILECOIN_BTC_B = -11.004
DEFAULT_MONERO_BTC_A = -2.164
DEFAULT_MONERO_BTC_B = -0.027
DEFAULT_LITECOIN_BTC_A = 5.578
DEFAULT_LITECOIN_BTC_B = -2.206
DEFAULT_DOGECOIN_BTC_A = -12.023
DEFAULT_DOGECOIN_BTC_B = 1.671
POWERLAW_INTERCEPT_MIN = -45.0
POWERLAW_INTERCEPT_MAX = 45.0
POWERLAW_SLOPE_MIN = 1.0
POWERLAW_SLOPE_MAX = 15.0
OSC_DEFAULTS = {
    "lambda_val": 2.01,
    "t1_age": 1.24,
    "amp_factor_top": 1.00,
    "amp_factor_bottom": 0.78,
    "impulse_damping": 1.72,
}
OSC_DEFAULTS_DIFFICULTY = {
    "lambda_val": 5.34,
    "t1_age": 1.51,
    "amp_factor_top": 0.69,
    "amp_factor_bottom": 0.78,
    "impulse_damping": 0.25,
}
OSC_DEFAULTS_HASHRATE = {
    "lambda_val": 5.47,
    "t1_age": 1.47,
    "amp_factor_top": 0.68,
    "amp_factor_bottom": 0.74,
    "impulse_damping": 0.11,
}

# Forecast limits
DEFAULT_FORECAST_HORIZON = 6
FORECAST_HORIZON_MIN = 1
FORECAST_HORIZON_MAX = 100
PORTFOLIO_RESET_A = -45.0
PORTFOLIO_RESET_B = 1.0
POWERLAW_EXPONENT_MIN = -300.0
POWERLAW_EXPONENT_MAX = 300.0

# Session-state keys
KEY_THEME_MODE = "theme_mode"
KEY_LAST_MODE = "last_mode"
KEY_CHART_REVISION = "chart_revision"
KEY_MODE_SELECTOR = "mode_selector"
KEY_POWERLAW_SERIES = "powerlaw_series"
KEY_LOGPERIODIC_SERIES = "logperiodic_series"
KEY_CURRENCY_SELECTOR = "currency_selector"
KEY_TIME_SCALE = "time_scale"
KEY_BAND_METHOD = "band_method"
KEY_GENESIS_OFFSET = "genesis_offset"
KEY_A = "A"
KEY_B = "B"
KEY_A_PRICE = "A_price"
KEY_B_PRICE = "B_price"
KEY_A_EURO = "A_euro"
KEY_B_EURO = "B_euro"
KEY_A_GOLD = "A_gold"
KEY_B_GOLD = "B_gold"
KEY_A_REVENUE = "A_revenue"
KEY_B_REVENUE = "B_revenue"
KEY_A_DIFFICULTY = "A_difficulty"
KEY_B_DIFFICULTY = "B_difficulty"
KEY_A_HASHRATE = "A_hashrate"
KEY_B_HASHRATE = "B_hashrate"
KEY_A_LIGHTNING_NODES = "A_lightning_nodes"
KEY_B_LIGHTNING_NODES = "B_lightning_nodes"
KEY_A_LIGHTNING_CAPACITY = "A_lightning_capacity"
KEY_B_LIGHTNING_CAPACITY = "B_lightning_capacity"
KEY_A_LIQUID_BTC = "A_liquid_btc"
KEY_B_LIQUID_BTC = "B_liquid_btc"
KEY_A_LIQUID_TRANSACTIONS = "A_liquid_transactions"
KEY_B_LIQUID_TRANSACTIONS = "B_liquid_transactions"
KEY_A_FILECOIN_BTC = "A_filecoin_btc"
KEY_B_FILECOIN_BTC = "B_filecoin_btc"
KEY_A_MONERO_BTC = "A_monero_btc"
KEY_B_MONERO_BTC = "B_monero_btc"
KEY_A_LITECOIN_BTC = "A_litecoin_btc"
KEY_B_LITECOIN_BTC = "B_litecoin_btc"
KEY_A_DOGECOIN_BTC = "A_dogecoin_btc"
KEY_B_DOGECOIN_BTC = "B_dogecoin_btc"
KEY_POWERLAW_AUTO_FIT = "powerlaw_auto_fit"
KEY_LOGPERIODIC_AUTO_FIT = "logperiodic_auto_fit"
KEY_LOGPERIODIC_LAST_SERIES = "logperiodic_last_series"
KEY_OSC_AUTOFIT_SIGNATURE = "osc_autofit_signature"
KEY_OSC_AUTOFIT_BEST_PARAMS = "osc_autofit_best_params"
KEY_PORTFOLIO_BTC_AMOUNT = "portfolio_btc_amount"
KEY_PORTFOLIO_MONTHLY_BUY_AMOUNT = "portfolio_monthly_buy_amount"
KEY_PORTFOLIO_FORECAST_UNIT = "portfolio_forecast_unit"
KEY_PORTFOLIO_FORECAST_HORIZON = "portfolio_forecast_horizon"
KEY_PORTFOLIO_FORECAST_MONTHS_LEGACY = "portfolio_forecast_months"

# UI options
MODE_POWERLAW = "PowerLaw"
MODE_LOGPERIODIC = "LogPeriodic"
MODE_PORTFOLIO = "Portfolio"
POWERLAW_SERIES_PRICE = "Bitcoin"
POWERLAW_SERIES_REVENUE = "Miner revenue"
POWERLAW_SERIES_DIFFICULTY = "Difficulty"
POWERLAW_SERIES_HASHRATE = "Hashrate"
POWERLAW_SERIES_LIGHTNING_NODES = "Lightning nodes"
POWERLAW_SERIES_LIGHTNING_CAPACITY = "Lightning BTC"
POWERLAW_SERIES_LIQUID_BTC = "Liquid BTC"
POWERLAW_SERIES_LIQUID_TRANSACTIONS = "Liquid transactions"
POWERLAW_SERIES_FILECOIN_BTC = "Filecoin / BTC"
POWERLAW_SERIES_MONERO_BTC = "Monero / BTC"
POWERLAW_SERIES_LITECOIN_BTC = "Litecoin / BTC"
POWERLAW_SERIES_DOGECOIN_BTC = "Dogecoin / BTC"
POWERLAW_SERIES_OPTIONS = [
    POWERLAW_SERIES_PRICE,
    POWERLAW_SERIES_REVENUE,
    POWERLAW_SERIES_DIFFICULTY,
    POWERLAW_SERIES_HASHRATE,
    POWERLAW_SERIES_LIGHTNING_NODES,
    POWERLAW_SERIES_LIGHTNING_CAPACITY,
    POWERLAW_SERIES_LIQUID_BTC,
    POWERLAW_SERIES_LIQUID_TRANSACTIONS,
    POWERLAW_SERIES_FILECOIN_BTC,
    POWERLAW_SERIES_MONERO_BTC,
    POWERLAW_SERIES_LITECOIN_BTC,
    POWERLAW_SERIES_DOGECOIN_BTC,
]
LOGPERIODIC_SERIES_OPTIONS = [
    POWERLAW_SERIES_PRICE,
    POWERLAW_SERIES_DIFFICULTY,
    POWERLAW_SERIES_HASHRATE,
]
CURRENCY_DOLLAR = "USD"
CURRENCY_EURO = "EUR"
CURRENCY_GOLD = "GOLD"
CURRENCY_OPTIONS = [CURRENCY_DOLLAR, CURRENCY_EURO, CURRENCY_GOLD]
TIME_LOG = "Log"
TIME_LIN = "Lin"
BAND_METHOD_QUANTILE = "Quantile"
BAND_METHOD_GAUSSIAN = "Gaussian"
BAND_METHOD_OPTIONS = [BAND_METHOD_QUANTILE, BAND_METHOD_GAUSSIAN]
THEME_OPTIONS = ["Dark 🌑"]
DEFAULT_THEME = THEME_OPTIONS[0]
