import pandas as pd

# App/meta
APP_VERSION = "1.1.43"
GENESIS_DATE = pd.to_datetime("2009-01-03")
DIFFICULTY_HASHRATE_ANALYSIS_START_DATE = pd.to_datetime("2010-01-01")
DIFFICULTY_HASHRATE_ANALYSIS_START_ABS_DAYS = int(
    (DIFFICULTY_HASHRATE_ANALYSIS_START_DATE - GENESIS_DATE).days
)
LIGHTNING_MODEL_ORIGIN_DATE = pd.to_datetime("2018-01-18")
LIQUID_BTC_MODEL_ORIGIN_DATE = pd.to_datetime("2018-08-31")
LIQUID_TRANSACTIONS_MODEL_ORIGIN_DATE = pd.to_datetime("2018-09-23")
FILECOIN_BTC_MODEL_ORIGIN_DATE = pd.to_datetime("2020-08-24")
MONERO_BTC_MODEL_ORIGIN_DATE = pd.to_datetime("2014-04-18")
LITECOIN_BTC_MODEL_ORIGIN_DATE = pd.to_datetime("2011-10-07")
DOGECOIN_BTC_MODEL_ORIGIN_DATE = pd.to_datetime("2013-12-06")
US_M2_MODEL_ORIGIN_DATE = pd.to_datetime("1958-12-31")
USDT_SUPPLY_MODEL_ORIGIN_DATE = pd.to_datetime("2017-11-29")
LIGHTNING_MODEL_ORIGIN_ABS_DAYS = int((LIGHTNING_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
LIQUID_BTC_MODEL_ORIGIN_ABS_DAYS = int((LIQUID_BTC_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
LIQUID_TRANSACTIONS_MODEL_ORIGIN_ABS_DAYS = int(
    (LIQUID_TRANSACTIONS_MODEL_ORIGIN_DATE - GENESIS_DATE).days
)
FILECOIN_BTC_MODEL_ORIGIN_ABS_DAYS = int((FILECOIN_BTC_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
MONERO_BTC_MODEL_ORIGIN_ABS_DAYS = int((MONERO_BTC_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
LITECOIN_BTC_MODEL_ORIGIN_ABS_DAYS = int((LITECOIN_BTC_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
DOGECOIN_BTC_MODEL_ORIGIN_ABS_DAYS = int((DOGECOIN_BTC_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
US_M2_MODEL_ORIGIN_ABS_DAYS = int((US_M2_MODEL_ORIGIN_DATE - GENESIS_DATE).days)
USDT_SUPPLY_MODEL_ORIGIN_ABS_DAYS = int((USDT_SUPPLY_MODEL_ORIGIN_DATE - GENESIS_DATE).days)

# Model defaults
DEFAULT_A = -16.444
DEFAULT_B = 5.670
DEFAULT_EURO_A = -16.908
DEFAULT_EURO_B = 5.783
DEFAULT_UAH_A = -18.286
DEFAULT_UAH_B = 6.581
DEFAULT_RUB_A = -16.713
DEFAULT_RUB_B = 6.253
DEFAULT_GOLD_A = -18.650
DEFAULT_GOLD_B = 5.378
DEFAULT_SILVER_A = -17.713
DEFAULT_SILVER_B = 5.643
DEFAULT_COPPER_A = -16.678
DEFAULT_COPPER_B = 5.585
DEFAULT_ALUMINUM_A = -19.520
DEFAULT_ALUMINUM_B = 5.594
DEFAULT_IRON_A = -18.868
DEFAULT_IRON_B = 5.790
DEFAULT_OIL_A = -18.835
DEFAULT_OIL_B = 5.830
DEFAULT_US_HOUSING_A = -17.205
DEFAULT_US_HOUSING_B = 5.219
DEFAULT_REVENUE_A = -7.843
DEFAULT_REVENUE_B = 4.149
DEFAULT_BITCOIN_MARKET_CAP_A = -11.325
DEFAULT_BITCOIN_MARKET_CAP_B = 6.260
DEFAULT_BITCOIN_VOLATILITY_A = 2.014
DEFAULT_BITCOIN_VOLATILITY_B = -0.432
DEFAULT_DIFFICULTY_A = -29.136
DEFAULT_DIFFICULTY_B = 11.616
DEFAULT_HASHRATE_A = -33.993
DEFAULT_HASHRATE_B = 11.538
DEFAULT_LIGHTNING_NODES_A = 1.297
DEFAULT_LIGHTNING_NODES_B = 0.869
DEFAULT_LIGHTNING_CAPACITY_A = -1.515
DEFAULT_LIGHTNING_CAPACITY_B = 1.550
DEFAULT_LIQUID_BTC_A = -2.697
DEFAULT_LIQUID_BTC_B = 1.935
DEFAULT_LIQUID_TRANSACTIONS_A = 0.440
DEFAULT_LIQUID_TRANSACTIONS_B = 1.114
DEFAULT_FILECOIN_BTC_A = 0.059
DEFAULT_FILECOIN_BTC_B = -1.333
DEFAULT_MONERO_BTC_A = -2.660
DEFAULT_MONERO_BTC_B = 0.123
DEFAULT_LITECOIN_BTC_A = 2.652
DEFAULT_LITECOIN_BTC_B = -1.452
DEFAULT_DOGECOIN_BTC_A = -7.529
DEFAULT_DOGECOIN_BTC_B = 0.463
DEFAULT_US_M2_A = -0.773
DEFAULT_US_M2_B = 1.073
DEFAULT_USDT_SUPPLY_A = -8.062
DEFAULT_USDT_SUPPLY_B = 3.002
POWERLAW_INTERCEPT_MIN = -45.0
POWERLAW_INTERCEPT_MAX = 45.0
POWERLAW_SLOPE_MIN = 1.0
POWERLAW_SLOPE_MAX = 15.0
OSC_DEFAULTS = {
    "lambda_val": 2.06,
    "t1_age": 1.74,
    "harmonic_count": 3,
}
OSC_DEFAULTS_EURO = {
    "lambda_val": 2.06,
    "t1_age": 0.59,
    "harmonic_count": 3,
}
OSC_DEFAULTS_UAH = {
    "lambda_val": 2.06,
    "t1_age": 1.74,
    "harmonic_count": 3,
}
OSC_DEFAULTS_RUB = {
    "lambda_val": 2.06,
    "t1_age": 0.59,
    "harmonic_count": 3,
}
OSC_DEFAULTS_GOLD = {
    "lambda_val": 2.07,
    "t1_age": 2.49,
    "harmonic_count": 3,
}
OSC_DEFAULTS_SILVER = {
    "lambda_val": 2.07,
    "t1_age": 2.50,
    "harmonic_count": 3,
}
OSC_DEFAULTS_COPPER = {
    "lambda_val": 2.06,
    "t1_age": 0.59,
    "harmonic_count": 3,
}
OSC_DEFAULTS_ALUMINUM = {
    "lambda_val": 2.06,
    "t1_age": 0.59,
    "harmonic_count": 3,
}
OSC_DEFAULTS_IRON = {
    "lambda_val": 2.06,
    "t1_age": 2.33,
    "harmonic_count": 3,
}
OSC_DEFAULTS_OIL = {
    "lambda_val": 2.06,
    "t1_age": 0.59,
    "harmonic_count": 3,
}
OSC_DEFAULTS_US_HOUSING = {
    "lambda_val": 2.06,
    "t1_age": 1.21,
    "harmonic_count": 3,
}
OSC_DEFAULTS_DIFFICULTY = {
    "lambda_val": 4.00,
    "t1_age": 2.00,
    "harmonic_count": 3,
}
OSC_DEFAULTS_HASHRATE = {
    "lambda_val": 4.05,
    "t1_age": 1.97,
    "harmonic_count": 3,
}

# Forecast limits
DEFAULT_FORECAST_HORIZON = 60
FORECAST_HORIZON_MIN = 1
FORECAST_HORIZON_MAX = 120
PORTFOLIO_RESET_A = -45.0
PORTFOLIO_RESET_B = 1.0
POWERLAW_EXPONENT_MIN = -300.0
POWERLAW_EXPONENT_MAX = 300.0

# Session-state keys
KEY_THEME_MODE = "theme_mode"
KEY_LAST_MODE = "last_mode"
KEY_CHART_REVISION = "chart_revision"
KEY_MODE_SELECTOR = "mode_selector"
KEY_POWERLAW_SERIES = "powerlaw_series"
KEY_LOGPERIODIC_SERIES = "logperiodic_series"
KEY_CURRENCY_SELECTOR = "currency_selector"
KEY_TIME_SCALE = "time_scale"
KEY_GENESIS_OFFSET = "genesis_offset"
KEY_A = "A"
KEY_B = "B"
KEY_A_PRICE = "A_price"
KEY_B_PRICE = "B_price"
KEY_A_EURO = "A_euro"
KEY_B_EURO = "B_euro"
KEY_A_UAH = "A_uah"
KEY_B_UAH = "B_uah"
KEY_A_RUB = "A_rub"
KEY_B_RUB = "B_rub"
KEY_A_GOLD = "A_gold"
KEY_B_GOLD = "B_gold"
KEY_A_SILVER = "A_silver"
KEY_B_SILVER = "B_silver"
KEY_A_COPPER = "A_copper"
KEY_B_COPPER = "B_copper"
KEY_A_ALUMINUM = "A_aluminum"
KEY_B_ALUMINUM = "B_aluminum"
KEY_A_IRON = "A_iron"
KEY_B_IRON = "B_iron"
KEY_A_OIL = "A_oil"
KEY_B_OIL = "B_oil"
KEY_A_US_HOUSING = "A_us_housing"
KEY_B_US_HOUSING = "B_us_housing"
KEY_A_REVENUE = "A_revenue"
KEY_B_REVENUE = "B_revenue"
KEY_A_BITCOIN_MARKET_CAP = "A_bitcoin_market_cap"
KEY_B_BITCOIN_MARKET_CAP = "B_bitcoin_market_cap"
KEY_A_BITCOIN_VOLATILITY = "A_bitcoin_volatility"
KEY_B_BITCOIN_VOLATILITY = "B_bitcoin_volatility"
KEY_A_DIFFICULTY = "A_difficulty"
KEY_B_DIFFICULTY = "B_difficulty"
KEY_A_HASHRATE = "A_hashrate"
KEY_B_HASHRATE = "B_hashrate"
KEY_A_LIGHTNING_NODES = "A_lightning_nodes"
KEY_B_LIGHTNING_NODES = "B_lightning_nodes"
KEY_A_LIGHTNING_CAPACITY = "A_lightning_capacity"
KEY_B_LIGHTNING_CAPACITY = "B_lightning_capacity"
KEY_A_LIQUID_BTC = "A_liquid_btc"
KEY_B_LIQUID_BTC = "B_liquid_btc"
KEY_A_LIQUID_TRANSACTIONS = "A_liquid_transactions"
KEY_B_LIQUID_TRANSACTIONS = "B_liquid_transactions"
KEY_A_FILECOIN_BTC = "A_filecoin_btc"
KEY_B_FILECOIN_BTC = "B_filecoin_btc"
KEY_A_MONERO_BTC = "A_monero_btc"
KEY_B_MONERO_BTC = "B_monero_btc"
KEY_A_LITECOIN_BTC = "A_litecoin_btc"
KEY_B_LITECOIN_BTC = "B_litecoin_btc"
KEY_A_DOGECOIN_BTC = "A_dogecoin_btc"
KEY_B_DOGECOIN_BTC = "B_dogecoin_btc"
KEY_A_US_M2 = "A_us_m2"
KEY_B_US_M2 = "B_us_m2"
KEY_A_USDT_SUPPLY = "A_usdt_supply"
KEY_B_USDT_SUPPLY = "B_usdt_supply"
KEY_A_BITCOIN_NETWORK_SIMULATION = "A_bitcoin_network_simulation"
KEY_B_BITCOIN_NETWORK_SIMULATION = "B_bitcoin_network_simulation"
KEY_BITCOIN_NETWORK_SIMULATION_SEED = "bitcoin_network_simulation_seed"
KEY_BITCOIN_NETWORK_SIMULATION_RESOLUTION = "bitcoin_network_simulation_resolution"
KEY_POWERLAW_AUTO_FIT = "powerlaw_auto_fit"
KEY_POWERLAW_ENVELOPE_SIGMA = "powerlaw_envelope_sigma"
KEY_LOGPERIODIC_AUTO_FIT = "logperiodic_auto_fit"
KEY_LOGPERIODIC_LAST_SERIES = "logperiodic_last_series"
KEY_LOGPERIODIC_HARMONICS = "logperiodic_harmonics"
KEY_LOGPERIODIC_SHOW_DECAYED_DSI = "logperiodic_show_decayed_dsi"
KEY_OSC_AUTOFIT_SIGNATURE = "osc_autofit_signature"
KEY_OSC_AUTOFIT_BEST_PARAMS = "osc_autofit_best_params"
KEY_SIGMA_BAND_HISTORY_RANGE_PCT = "sigma_band_history_range_pct"
KEY_SIGMA_BAND_HISTORY_YEARS = "sigma_band_history_years"
KEY_PORTFOLIO_BTC_AMOUNT = "portfolio_btc_amount"
KEY_PORTFOLIO_MONTHLY_BUY_AMOUNT = "portfolio_monthly_buy_amount"
KEY_PORTFOLIO_MONTHLY_MOM_CHANGE_PCT = "portfolio_monthly_mom_change_pct"
KEY_PORTFOLIO_PENSION_DIVISOR = "portfolio_pension_divisor"
KEY_PORTFOLIO_PENSION_PAYOUT_PCT = "portfolio_pension_payout_pct"
KEY_PORTFOLIO_STRATEGY_VIEW = "portfolio_strategy_view"
KEY_PORTFOLIO_SIGMA_LEVEL = "portfolio_sigma_level"
PORTFOLIO_SIGMA_CURRENT = "current"
PORTFOLIO_SIGMA_PEAK_POWERLAW = "peak_powerlaw"
PORTFOLIO_SIGMA_TROUGH_POWERLAW = "trough_powerlaw"
PORTFOLIO_VIEW_ACCUMULATION = "Accumulation"
PORTFOLIO_VIEW_PENSION = "Pension"
PORTFOLIO_VIEW_STRATEGY_TESTER = "Strategy tester"
KEY_PORTFOLIO_FORECAST_UNIT = "portfolio_forecast_unit"
KEY_PORTFOLIO_FORECAST_HORIZON = "portfolio_forecast_horizon"
KEY_PORTFOLIO_FORECAST_MONTHS_LEGACY = "portfolio_forecast_months"
KEY_PORTFOLIO_BACKTEST_STRATEGY_PCT = "portfolio_backtest_strategy_pct"
KEY_PORTFOLIO_BACKTEST_FLOOR_MODEL = "portfolio_backtest_floor_model"
KEY_PORTFOLIO_BACKTEST_YEARS = "portfolio_backtest_years"
KEY_PORTFOLIO_BACKTEST_INITIAL_CAPITAL = "portfolio_backtest_initial_capital"
KEY_PORTFOLIO_BACKTEST_HAS_RUN = "portfolio_backtest_has_run"

# UI options
MODE_POWERLAW = "PowerLaw"
MODE_LOGPERIODIC = "LogPeriodic"
MODE_PORTFOLIO = "Portfolio"
POWERLAW_SERIES_PRICE = "Bitcoin"
POWERLAW_SERIES_REVENUE = "Miner revenue"
POWERLAW_SERIES_BITCOIN_MARKET_CAP = "Bitcoin market cap"
POWERLAW_SERIES_BITCOIN_VOLATILITY = "Bitcoin volatility"
POWERLAW_SERIES_DIFFICULTY = "Difficulty"
POWERLAW_SERIES_HASHRATE = "Hashrate"
POWERLAW_SERIES_BITCOIN_NETWORK_SIMULATION = "Bitcoin network simulation"
POWERLAW_SERIES_LIGHTNING_NODES = "Lightning nodes"
POWERLAW_SERIES_LIGHTNING_CAPACITY = "Lightning BTC"
POWERLAW_SERIES_LIQUID_BTC = "Liquid BTC"
POWERLAW_SERIES_LIQUID_TRANSACTIONS = "Liquid transactions"
POWERLAW_SERIES_FILECOIN_BTC = "Filecoin / BTC"
POWERLAW_SERIES_MONERO_BTC = "Monero / BTC"
POWERLAW_SERIES_LITECOIN_BTC = "Litecoin / BTC"
POWERLAW_SERIES_DOGECOIN_BTC = "Dogecoin / BTC"
POWERLAW_SERIES_US_M2 = "U.S. M2"
POWERLAW_SERIES_USDT_SUPPLY = "USDT supply"
POWERLAW_SERIES_OPTIONS = [
    POWERLAW_SERIES_PRICE,
    POWERLAW_SERIES_REVENUE,
    POWERLAW_SERIES_BITCOIN_MARKET_CAP,
    POWERLAW_SERIES_BITCOIN_VOLATILITY,
    POWERLAW_SERIES_DIFFICULTY,
    POWERLAW_SERIES_HASHRATE,
    POWERLAW_SERIES_BITCOIN_NETWORK_SIMULATION,
    POWERLAW_SERIES_LIGHTNING_CAPACITY,
    POWERLAW_SERIES_LIGHTNING_NODES,
    POWERLAW_SERIES_LIQUID_BTC,
    POWERLAW_SERIES_LIQUID_TRANSACTIONS,
    POWERLAW_SERIES_FILECOIN_BTC,
    POWERLAW_SERIES_MONERO_BTC,
    POWERLAW_SERIES_LITECOIN_BTC,
    POWERLAW_SERIES_DOGECOIN_BTC,
    POWERLAW_SERIES_US_M2,
    POWERLAW_SERIES_USDT_SUPPLY,
]
LOGPERIODIC_SERIES_OPTIONS = [
    POWERLAW_SERIES_PRICE,
    POWERLAW_SERIES_DIFFICULTY,
    POWERLAW_SERIES_HASHRATE,
]
CURRENCY_DOLLAR = "USD"
CURRENCY_EURO = "EUR"
CURRENCY_UAH = "UAH"
CURRENCY_RUB = "RUB"
CURRENCY_GOLD = "GOLD"
CURRENCY_SILVER = "SILVER"
CURRENCY_COPPER = "COPPER"
CURRENCY_ALUMINUM = "ALUMINUM"
CURRENCY_IRON = "IRON"
CURRENCY_OIL = "OIL"
CURRENCY_US_HOUSING = "US_HOUSING"
CURRENCY_OPTIONS = [
    CURRENCY_EURO,
    CURRENCY_DOLLAR,
    CURRENCY_UAH,
    CURRENCY_RUB,
    CURRENCY_GOLD,
    CURRENCY_SILVER,
    CURRENCY_COPPER,
    CURRENCY_ALUMINUM,
    CURRENCY_IRON,
    CURRENCY_OIL,
    CURRENCY_US_HOUSING,
]
TIME_LOG = "Log"
TIME_LIN = "Lin"
THEME_OPTIONS = ["Dark 🌑"]
DEFAULT_THEME = THEME_OPTIONS[0]
